spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
env:
  dev2
girl:
  name: lisi
  age: 33
